name: Auto release

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: "softprops/action-gh-release@v1"
        with:
          prerelease: true
          name: "Development Build"
          tag_name: "dev"
          files: |
            include/*.h